import json
import csv
from datetime import datetime
from jinja2 import Template

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>ReconDorker Report - {{ target }}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f4f4f9; color: #333; margin: 0; padding: 20px; }
        .container { max-width: 1000px; margin: auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        .result { border-bottom: 1px solid #eee; padding: 15px 0; }
        .result a { color: #3498db; text-decoration: none; font-weight: bold; }
        .result a:hover { text-decoration: underline; }
        .snippet { font-size: 0.9em; color: #666; margin-top: 5px; }
        .footer { margin-top: 30px; font-size: 0.8em; text-align: center; color: #999; }
    </style>
</head>
<body>
    <div class="container">
        <h1>ReconDorker Report: {{ target }}</h1>
        <p>Generated at: {{ timestamp }}</p>
        <div class="results">
            {% for result in results %}
            <div class="result">
                <a href="{{ result.link }}" target="_blank">{{ result.title }}</a>
                <div class="snippet">{{ result.snippet }}</div>
            </div>
            {% endfor %}
        </div>
        <div class="footer">Generated by ReconDorker</div>
    </div>
</body>
</html>
"""

class Reporter:
    @staticmethod
    def to_json(results, output_file):
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(results, f, indent=4)

    @staticmethod
    def to_csv(results, output_file):
        if not results:
            return
        keys = results[0].keys()
        with open(output_file, 'w', newline='', encoding='utf-8') as f:
            dict_writer = csv.DictWriter(f, fieldnames=keys)
            dict_writer.writeheader()
            dict_writer.writerows(results)

    @staticmethod
    def to_html(target, results, output_file):
        template = Template(HTML_TEMPLATE)
        html_content = template.render(
            target=target,
            results=results,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        )
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(html_content)
